name: Release

on:
  release:
    types: [published]

permissions: read-all

jobs:
  release:
    name: Release
    environment:
      name: pypi
      url: https://pypi.org/p/magi-cli
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: |
          pip install --upgrade pip
          pip --version

      - name: Install Poetry
        run: |
          pipx install poetry
          pipx inject poetry poetry-plugin-export
          poetry config warnings.export false
          poetry export --without-hashes --format=requirements.txt > constraints.txt
          poetry --version

      - name: Bump version for developmental release
        run: |
          poetry version ${{ github.ref_name }}

      - name: Build package
        run: |
          poetry build --ansi

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.ref }}
          body: ${{ github.event.release.body }}
          file_glob: true

      - name: Publish package on PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.14

    #  - name: Publish package on TestPyPI
    #    uses: pypa/gh-action-pypi-publish@v1.8.14
